/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.formdev:flatlaf:2.6")
    implementation("com.formdev:flatlaf-intellij-themes:2.6")
    implementation("com.formdev:flatlaf-swingx:2.6")
    implementation("org.netbeans.external:AbsoluteLayout:RELEASE150")
    implementation("org.swinglabs.swingx:swingx-all:1.6.5-1")
    implementation("org.json:json:20080701")
    implementation("com.google.code.gson:gson:2.10")
}

group = "MyStudyPlan"
version = "1.0"
description = "MyStudyPlan"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}
