/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyStudyPlan;

import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.BorderFactory;

/**
 *
 * @author Dulapah Vibulsanti
 */
public class ManageSubjects extends javax.swing.JFrame {

    /**
     * Creates new form NewTask
     */
    public ManageSubjects() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TopBanner = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CodeTxt = new javax.swing.JLabel();
        CodeTxtField = new javax.swing.JTextField();
        SubjectTxt = new javax.swing.JLabel();
        SubjectTxtField = new javax.swing.JTextField();
        ColorTxt = new javax.swing.JLabel();
        ColorTxtField = new javax.swing.JTextField();
        SubjectAddBtn = new javax.swing.JButton();
        SubjectRemoveBtn = new javax.swing.JButton();
        SubjectsScrollPane = new javax.swing.JScrollPane();
        SubjectsTable = new javax.swing.JTable();
        CancelBtn = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Subjects");
        setResizable(false);

        TopBanner.setBackground(new java.awt.Color(59, 162, 191));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Manage Subjects");

        javax.swing.GroupLayout TopBannerLayout = new javax.swing.GroupLayout(TopBanner);
        TopBanner.setLayout(TopBannerLayout);
        TopBannerLayout.setHorizontalGroup(
            TopBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopBannerLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TopBannerLayout.setVerticalGroup(
            TopBannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopBannerLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        CodeTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        CodeTxt.setText("Code");

        CodeTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        SubjectTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        SubjectTxt.setText("Subject");

        SubjectTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        ColorTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ColorTxt.setText("Color");

        ColorTxtField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ColorTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ColorTxtFieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ColorTxtFieldMousePressed(evt);
            }
        });

        SubjectAddBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SubjectAddBtn.setText("+");
        SubjectAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectAddBtnActionPerformed(evt);
            }
        });

        SubjectRemoveBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SubjectRemoveBtn.setText("-");
        SubjectRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectRemoveBtnActionPerformed(evt);
            }
        });

        SubjectsTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SubjectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, ""},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Code", "Subjects"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SubjectsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SubjectsTable.setShowGrid(false);
        SubjectsTable.setShowVerticalLines(true);
        SubjectsTable.getTableHeader().setReorderingAllowed(false);
        SubjectsScrollPane.setViewportView(SubjectsTable);
        if (SubjectsTable.getColumnModel().getColumnCount() > 0) {
            SubjectsTable.getColumnModel().getColumn(0).setResizable(false);
            SubjectsTable.getColumnModel().getColumn(1).setResizable(false);
            SubjectsTable.getColumnModel().getColumn(1).setPreferredWidth(450);
        }

        CancelBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        CancelBtn.setText("Cancel");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        SaveBtn.setBackground(new java.awt.Color(59, 162, 191));
        SaveBtn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        SaveBtn.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SaveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CodeTxt)
                                    .addComponent(CodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubjectTxtField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(SubjectTxt)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ColorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SubjectAddBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SubjectRemoveBtn))
                                    .addComponent(ColorTxt)))
                            .addComponent(SubjectsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))))
                .addGap(38, 38, 38))
            .addComponent(TopBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TopBanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SubjectAddBtn)
                        .addComponent(SubjectRemoveBtn)
                        .addComponent(ColorTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodeTxt)
                            .addComponent(SubjectTxt)
                            .addComponent(ColorTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CodeTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SubjectTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(SubjectsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveBtn)
                    .addComponent(CancelBtn))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubjectAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectAddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectAddBtnActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void SubjectRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectRemoveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubjectRemoveBtnActionPerformed

    private void ColorTxtFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorTxtFieldMouseClicked
        ColorPicker cp = new ColorPicker();
        cp.setLocationRelativeTo(null);
        cp.setLocation(cp.getX(), cp.getY() + 115);
        cp.setVisible(true);
        this.setEnabled(false);
        cp.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.decode("#3BA2BF")));
        cp.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                ManageSubjects.this.setEnabled(true);
                ManageSubjects.this.requestFocus();
                ManageSubjects.this.setExtendedState(ManageSubjects.this.getExtendedState() & ~ManageSubjects.ICONIFIED);
                ColorTxtField.setText(cp.getHexValue());
                ColorTxtField.setForeground(new Color(Integer.parseInt(cp.getHexValue().substring(1), 16)));
            }
        });
    }//GEN-LAST:event_ColorTxtFieldMouseClicked

    private void ColorTxtFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ColorTxtFieldMousePressed
        ColorPicker cp = new ColorPicker();
        cp.setLocationRelativeTo(null);
        cp.setLocation(cp.getX(), cp.getY() + 115);
        cp.setVisible(true);
        this.setEnabled(false);
        cp.getRootPane().setBorder(BorderFactory.createMatteBorder(3, 3, 3, 3, Color.decode("#3BA2BF")));
        cp.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                ManageSubjects.this.setEnabled(true);
                ManageSubjects.this.requestFocus();
                ManageSubjects.this.setExtendedState(ManageSubjects.this.getExtendedState() & ~ManageSubjects.ICONIFIED);
                ColorTxtField.setText(cp.getHexValue());
                ColorTxtField.setForeground(new Color(Integer.parseInt(cp.getHexValue().substring(1), 16)));
            }
        });
    }//GEN-LAST:event_ColorTxtFieldMousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NewTask().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JLabel CodeTxt;
    private javax.swing.JTextField CodeTxtField;
    private javax.swing.JLabel ColorTxt;
    private javax.swing.JTextField ColorTxtField;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JButton SubjectAddBtn;
    private javax.swing.JButton SubjectRemoveBtn;
    private javax.swing.JLabel SubjectTxt;
    private javax.swing.JTextField SubjectTxtField;
    private javax.swing.JScrollPane SubjectsScrollPane;
    private javax.swing.JTable SubjectsTable;
    private javax.swing.JPanel TopBanner;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
